<?php

require_once 'dbsettings.php';

/**
 * IMPORTANT !!!!
 *
 * You must create a file name "dbsettings.php" in this directory
 * It should contains this:
 *
 * $etui_webform_db_params = [
 *   'host' => 'ETUIDBHOST',
 *   'user' => 'USER_NAME',
 *   'pwd' => 'PASSWORD',
 *   'db' => 'DATABASE NAME',
 * ];
 *
 */
function etui_webform_webform_select_options_info() {
  $items = [];

  $items['civicrm-organizations'] = array(
    'title' => 'EWC Bodies',
    'options callback' => '_etui_webform_getOrganizations',
  );

  return $items;
}

function _etui_webform_getOrganizations() {
  $organizationList = [];

  $dsn = sprintf('mysql:host=%s;dbname=%s;charset=utf8', $etui_webform_db_params['host'], $etui_webform_db_params['db']);
  $pdo = new PDO($dsn, $etui_webform_db_params['user'], $etui_webform_db_params['pwd']);

  $sql = "
    select
      body_ID id
      , concat(bodyname, ' (', bodygroup, ')') bodyname
    from
      active_bodies
    order by
      bodygroup, bodyname
  ";
  $stmt = $pdo->query($sql);

  while ($row = $stmt->fetch(PDO::FETCH_OBJ)) {
    $organizationList[$row->id] = $row->bodyname;
  }

  return $organizationList;
}
