<?php

function etui_webform_webform_select_options_info() {
  $items = [];

  $items['civicrm-organizations'] = array(
    'title' => 'EWC Bodies',
    'options callback' => '_etui_webform_getOrganizations',
  );

  return $items;
}

function _etui_webform_getOrganizations() {
  try {
    civicrm_initialize();

    $organizationList = [];

    // limit the number of records in edit mode
    if (strpos(current_path(), 'webform/components') !== FALSE || strpos(current_path(), 'webform/ajax') !== FALSE) {
      $limit = ' limit 0,5';
    }
    else {
      $limit = '';
    }

    $sql = "
      select
        c.id body_id,
        c.organization_name bodyname
      from
        civicrm_contact c
      inner join
        civicrm_value_ewc_216 ewc on c.id = ewc.entity_id
      where
        c.is_deleted = 0
      and
        c.contact_type = 'Organization'
      and
        c.contact_sub_type = 'European_Works_Council'
      and
        ifnull(ewc.replaced_by_531, '') = ''
      and
        ifnull(ewc.end_530, '') = ''    
      order by
        c.sort_name
      $limit
    ";
    $dao = CRM_Core_DAO::executeQuery($sql);

    while ($dao->fetch()) {
      $organizationList[$dao->body_id] = $dao->bodyname;
    }
  }
  catch (Exception $e) {
    $organizationList[1] = $e->getMessage();
  }

  return $organizationList;
}
